[package]
name = "pulsar-engine"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "pulsar-engine"
edition = "2021"
rust-version = "1.66"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde_json = "1.0"
tauri = { version = "1.8", features = [ "api-all"] }
walkdir = "2.5.0"
base64 = "0.22.1"
tron = "1.0.0"
parking_lot = "0.12.3"
log = "0.4.25"
env_logger = "0.10.2"
anyhow = "1.0.95"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["WebGl2RenderingContext", "WebGlProgram", "WebGlShader", "OffscreenCanvas", "HtmlCanvasElement", "Window", "Document"] }
# bevy = "0.15.1"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
